apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-test
  template:
    metadata:
      labels:
        app: django-test
    spec:
      containers:
        - name: django-test
          image: manjeetyadav19/django
          imagePullPolicy: Always
          ports:
          - name: django-test
            containerPort: 8000
            protocol: TCP
      imagePullSecrets:
        - name: regcred
...
---
apiVersion: v1
kind: Service
metadata:
  name: django-test-service
spec:
  type: ClusterIP
  selector:
    app: django-test
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
...
